### ISSUE TITLE
Compatibility with OJS 2.4

### ISSUE THREAD

**Issue by mendesrocha** [richardalberto/yiidhl#2]
Hello,

Do you think your plugin is compatible with OJS 2.4.0 ?

I've just installed it as guided at README. I uncompressed files to plugins/generic, then I enabled the plugin on generic plugins page, but I can't see any modification neither on Editor pages, nor on submission metadata edit page. The webpage

/index.php/{journal_abrevviatte}/articlesExtrasPlugin

is not accessible from browser.

I installed it to work with Scielo Export plugin, and this seems to work fine altought I cannot include the full article text on the generated xml.

Thanks in advance.
Renato

**Comment by richardalberto** [comment]
Hi Renato,
I think you got the wrong project. You should post this on the Articles Extras Plugin page.

Thanks.
